### PR TITLE
node text added

### PR DESCRIPTION
**Pull request by noghte**
In my scenario, having a different node value and node text was necessary. So, I have added text beside value for the tree nodes.

### CODE REVIEW

**Comment by helfi92** [comment]
What is the difference between `text` and `value`? I'm not sure sure I understand the use case of this. Clarifications would be appreciated.

**Comment by noghte** [comment]
For two reasons, first, I get a warning when having redundant values at the same level of the tree. Though it is not a common use-case to use similar labels for different nodes of a tree, it is possible. The warning says:
> Warning: Encountered two children with the same key, `PI4K`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

Second, users might need to have numeric or other meaningful values for their operations, however, they would like to show a plain text as a label. In my case, here is an example:
```
            {
                "value": "id653@PI3K",
                "text": "PI3K",
                "nodes": []
            },
            {
                "value": "id654@PI4K",
                "text": "PI4K",
                "nodes": []
            }
```
Similar to radtio buttons in HTML that can have different labels and values. An example:
https://demos.telerik.com/kendo-ui/treeview/templates

**Comment by helfi92** [comment]
You can make use of the `id` field that you can give to any node https://github.com/helfi92/material-ui-treeview/blob/master/src/components/MuiTreeView/index.jsx#L37. The benefit of using this key is twofold.

1. It gives you a way to set the `key` prop instead of relying on the `value` property. https://github.com/helfi92/material-ui-treeview/blob/master/src/components/MuiTreeView/index.jsx#L37. This should satisfy your first point.

2. The node will have the id so clicking on it will reveal its value. This should satisfy your second point.

**Comment by noghte** [comment]
Oh! I didn't see the "id" field. I should have asked before modifying the code! I'm going to close this pull request. Thanks for your replies.

**Comment by helfi92** [comment]
No problem! The README seems to fail to let users know about this property. Happy to accept a pull-request if you're up for it :-)

**Pull request closed without merging**
