### PR TITLE
Make search case insensitive. Fix for taskcluster 1754

### PR DESCRIPTION
**Pull request by Karskaya**
Add parameter caseInsensitiveSearch

Change search functionality(`filter(tree)`) to use regular expression instead of string

Fix StyleGuide import path

Add babel-plugin-transform-es2015-modules-commonjs and babel-plugin-transform-object-rest-spread to yarn devDependencies

## Checklist

- [x] Make sure there are no linter errors (run `yarn lint` to see the errors and `yarn lint --fix` to fix them)
- [x] Update the documentation file `README.md` if required
- [x] Update the Typescript declaration file `src/index.d.ts` if any exposed properties are removed/added

### CODE REVIEW

**Comment by Karskaya** [comment]
@helfi92 Please, review

**Comment by Karskaya** [comment]
> This would need a rebase on master. We recently just pushed a big update to this repo that migrates the repo to the latest version of material-ui.

Rebase cause a big merge conflict. So I'll take a look during a weekends.

**Comment by helfi92** [comment]
You can always close this pr and open a new one. It might be easier since there will be no code conflict.

**Comment by Karskaya** [comment]
@helfi92 you're right! it will be more logical.

**Pull request closed without merging**
